import Foundation
import Network
import AVFoundation
import Testing
@testable import TSPlayerKit

// MARK: - Dynamic "Twitch-like" origin

/// Serves a live sliding-window media playlist whose content segments are real
/// 2 s MPEG-TS files (generated by ffmpeg with monotonic PTS) and whose middle
/// is a programmable ad break (`#EXT-X-CUE-OUT`/`CUE-IN`, like Twitch).
final class DynamicOriginServer: @unchecked Sendable {
    private let listener: NWListener
    private let queue = DispatchQueue(label: "test.origin")
    private let readySemaphore = DispatchSemaphore(value: 0)
    private(set) var port: UInt16 = 0

    let adStartSegment: Int
    let adSegmentCount: Int
    private let startDate = Date()
    /// Content segment bytes by global index.
    private let segments: [Data]
    /// Bytes served for ad segments (never actually played — the proxy replaces them).
    private let adData: Data

    private static let dateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(identifier: "UTC")
        f.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
        return f
    }()

    init(segments: [Data], adData: Data, adStartSegment: Int, adSegmentCount: Int) throws {
        self.segments = segments
        self.adData = adData
        self.adStartSegment = adStartSegment
        self.adSegmentCount = adSegmentCount
        let params = NWParameters.tcp
        params.requiredLocalEndpoint = NWEndpoint.hostPort(host: .ipv4(.loopback), port: .any)
        let listener = try NWListener(using: params)
        self.listener = listener
        listener.stateUpdateHandler = { [weak self] state in
            guard let self else { return }
            if case .ready = state {
                self.port = listener.port?.rawValue ?? 0
                self.readySemaphore.signal()
            }
        }
        listener.newConnectionHandler = { [weak self] conn in self?.handle(conn) }
        listener.start(queue: queue)
        readySemaphore.wait()
    }

    var masterURL: URL { URL(string: "http://127.0.0.1:\(port)/playlist.m3u8")! }
    func stop() { listener.cancel() }

    /// Number of segments published so far (2 s each).
    private func publishedCount() -> Int {
        Int(Date().timeIntervalSince(startDate) / 2.0)
    }

    private func handle(_ connection: NWConnection) {
        connection.start(queue: queue)
        connection.receive(minimumIncompleteLength: 1, maximumLength: 65536) { [weak self] data, _, _, error in
            guard let self else { return }
            guard error == nil, let data else { connection.cancel(); return }
            let raw = String(data: data, encoding: .utf8) ?? ""
            let path = raw.components(separatedBy: " ").dropFirst().first ?? ""
            self.route(path: path.components(separatedBy: "?").first ?? path, on: connection)
        }
    }

    private func route(path: String, on connection: NWConnection) {
        if path == "/playlist.m3u8" {
            servePlaylist(on: connection)
            return
        }
        if path.hasPrefix("/seg") {
            let name = path.components(separatedBy: "/").last ?? ""
            // "seg12.ts" → 12 (drop the "seg" prefix AND the ".ts" suffix)
            let idx = Int(name
                .dropFirst(3)
                .replacingOccurrences(of: ".ts", with: ""))
            if let idx {
                let isAd = idx >= adStartSegment && idx < adStartSegment + adSegmentCount
                let body = isAd ? adData : (idx < segments.count ? segments[idx] : Data())
                send(200, body: body, contentType: "video/mp2t", on: connection)
                return
            }
        }
        send(404, body: Data(), contentType: "text/plain", on: connection)
    }

    private func servePlaylist(on connection: NWConnection) {
        let count = publishedCount()
        let first = max(0, count - 5)             // 6-segment sliding window
        // MEDIA-SEQUENCE = the window's first global index (base 0), so that
        // (sequence + position) × 2 s equals the ffmpeg content PTS — exactly
        // Twitch's scale, where content PTS ≈ stream uptime in seconds.
        var lines = [
            "#EXTM3U",
            "#EXT-X-TARGETDURATION:2",
            "#EXT-X-MEDIA-SEQUENCE:\(first)",
            "#EXT-X-SERVER-CONTROL:CAN-BLOCK-RELOAD=YES",
        ]
        for k in first...min(first + 5, count) {
            let date = startDate.addingTimeInterval(Double(k) * 2.0)
            lines.append("#EXT-X-PROGRAM-DATE-TIME:\(Self.dateFormatter.string(from: date))")
            if k == adStartSegment {
                lines.append("#EXT-X-CUE-OUT:\(Double(adSegmentCount * 2))")
            }
            lines.append("#EXTINF:2.000,")
            lines.append("seg\(k).ts")
            if k == adStartSegment + adSegmentCount - 1 {
                lines.append("#EXT-X-CUE-IN")
            }
        }
        send(200, body: Data((lines.joined(separator: "\n") + "\n").utf8),
             contentType: "application/vnd.apple.mpegurl", on: connection)
    }

    private func send(_ status: Int, body: Data, contentType: String, on connection: NWConnection) {
        let head = "HTTP/1.1 \(status) \(status == 200 ? "OK" : "Not Found")\r\n"
            + "Content-Type: \(contentType)\r\nContent-Length: \(body.count)\r\nConnection: close\r\n\r\n"
        var data = Data(head.utf8)
        data.append(body)
        connection.send(content: data, completion: .contentProcessed { _ in connection.cancel() })
    }
}

// MARK: - Real AVPlayer integration

@Suite("AVPlayerLiveIntegration", .serialized)
struct AVPlayerLiveIntegrationTests {

    /// Generates real 2 s H.264+AAC MPEG-TS segments with monotonic PTS
    /// (ffmpeg segment muxer). Returns the segment bytes in order.
    private static func generateSegments() throws -> [Data] {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("tskit-it-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        let ffmpeg = "/opt/homebrew/bin/ffmpeg"
        guard FileManager.default.isExecutableFile(atPath: ffmpeg) else {
            throw NSError(domain: "Test", code: 2,
                          userInfo: [NSLocalizedDescriptionKey: "ffmpeg not found at \(ffmpeg)"])
        }

        let process = Process()
        process.executableURL = URL(fileURLWithPath: ffmpeg)
        process.arguments = [
            "-hide_banner", "-loglevel", "error",
            "-f", "lavfi", "-i", "color=c=black:s=640x360:r=30:d=34",
            "-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo",
            "-t", "34",
            "-c:v", "libx264", "-preset", "ultrafast", "-tune", "zerolatency",
            "-force_key_frames", "expr:gte(t,n_forced*2)",
            "-c:a", "aac", "-b:a", "96k",
            "-f", "hls", "-hls_time", "2", "-hls_playlist_type", "vod",
            "-hls_segment_filename", "\(dir.path)/seg%d.ts",
            "\(dir.path)/out.m3u8",
        ]
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            throw NSError(domain: "Test", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: "ffmpeg failed (\(process.terminationStatus))"])
        }

        let files = try FileManager.default.contentsOfDirectory(atPath: dir.path)
            .filter { $0.hasPrefix("seg") && $0.hasSuffix(".ts") }
            .sorted { a, b in
                let na = Int(a.dropFirst(3).replacingOccurrences(of: ".ts", with: "")) ?? 0
                let nb = Int(b.dropFirst(3).replacingOccurrences(of: ".ts", with: "")) ?? 0
                return na < nb
            }
        return try files.map { try Data(contentsOf: dir.appendingPathComponent($0)) }
    }

    /// The exact production scenario: live playback starts, an ad break enters
    /// the sliding window mid-playback, the proxy substitutes slates, and the
    /// stream must survive the break and keep advancing.
    @Test("AVPlayer plays through a live ad break (slate substitution) without stalling")
    @MainActor
    func playbackSurvivesAdBreak() async throws {
        let segments = try Self.generateSegments()
        #expect(segments.count >= 10, "ffmpeg produced too few segments: \(segments.count)")

        let origin = try DynamicOriginServer(
            segments: segments,
            adData: SlateSegment.data ?? Data(),
            adStartSegment: 3,
            adSegmentCount: 5
        )
        defer { origin.stop() }

        let fetcher = RemotePlaylistFetcher(userAgent: "AVPlayerIntegrationTests")
        let proxy = try AdStrippingProxy(remoteURL: origin.masterURL, fetcher: fetcher)
        defer { proxy.stop() }

        let item = AVPlayerItem(asset: AVURLAsset(url: proxy.localURL))
        let player = AVPlayer(playerItem: item)

        let endTime = ContinuousClock.now + .seconds(40)
        var started = false
        var failed: Error?
        var maxTime: Double = 0

        while ContinuousClock.now < endTime, failed == nil {
            try await Task.sleep(nanoseconds: 250_000_000)

            if item.status == .readyToPlay, !started {
                started = true
                player.play()
            }
            if item.status == .failed {
                failed = item.error
            }
            let t = player.currentTime().seconds
            if t.isFinite, t > 0 {
                maxTime = max(maxTime, t)
            }
        }

        #expect(started, "AVPlayerItem never became ready")
        if let failed {
            #expect(Bool(false), "Playback failed: \(failed.localizedDescription)")
        }
        // Break: 5 × 2 s slates starting at t≈6 s (origin time). Surviving it
        // means the clock keeps advancing past ~13 s.
        #expect(maxTime >= 13,
                "Playback stalled during or after the ad break (maxTime=\(maxTime))")
    }
}
